# Generated by Django 5.1.1 on 2024-11-03 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coupon_codes',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='cart.coupon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='product_ratings',
            field=models.ManyToManyField(blank=True, related_name='rated_by', to='products.product'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shippingaddress'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wishlist_products',
            field=models.ManyToManyField(blank=True, related_name='wished_by', to='products.wishlist'),
        ),
    ]
